#ifndef PARAMETERS_MENU_H
#define PARAMETERS_MENU_H


/*
 * Перечисления типов для выбора в меню.
 */
//! Перечисление фаз.
MENU_VALUES(menu_enum_phases,
    MAKE_MENU_VALUE_STRING("Не задано"), MAKE_MENU_VALUE_STRING("Фаза A"),
    MAKE_MENU_VALUE_STRING("Фаза B"), MAKE_MENU_VALUE_STRING("Фаза C")
);
//! Перечисление Да/Нет.
MENU_VALUES(menu_enum_bool,
    MAKE_MENU_VALUE_STRING("Нет"), MAKE_MENU_VALUE_STRING("Да")
);
//! Перечисление Разрешено/Запрещено.
//MENU_VALUES(menu_enum_en_dis,
//    MAKE_MENU_VALUE_STRING("Запрещено"), MAKE_MENU_VALUE_STRING("Разрешено")
//);
//! Перечисление режима возбуждения.
MENU_VALUES(menu_enum_exc_mode,
    MAKE_MENU_VALUE_STRING("Фиксированное"), MAKE_MENU_VALUE_STRING("Регулируемое")
);
//! Перечисление типа останова.
MENU_VALUES(menu_enum_stop_mode,
    MAKE_MENU_VALUE_STRING("Нормальный"), MAKE_MENU_VALUE_STRING("Быстрый"), MAKE_MENU_VALUE_STRING("Выбег")
);
//! Перечисление действия защиты.
MENU_VALUES(menu_enum_prot_action,
    MAKE_MENU_VALUE_STRING("Игнорировать"), MAKE_MENU_VALUE_STRING("Предупреждение"), MAKE_MENU_VALUE_STRING("Быстрый останов"),
    MAKE_MENU_VALUE_STRING("Останов выбегом"), MAKE_MENU_VALUE_STRING("Экстренный останов")
);
//! Перечисление типа цифровых входов.
MENU_VALUES(menu_enum_dio_in_type,
    MAKE_MENU_VALUE_STRING("Не подключен"), MAKE_MENU_VALUE_STRING("Запуск/Останов"), MAKE_MENU_VALUE_STRING("Экстренный останов"),
    MAKE_MENU_VALUE_STRING("Инкремент задания"), MAKE_MENU_VALUE_STRING("Декремент задания"),
    MAKE_MENU_VALUE_STRING("Сброс ошибок"), MAKE_MENU_VALUE_STRING("Пользовательский")
);
//! Перечисление типа цифровых выходов.
MENU_VALUES(menu_enum_dio_out_type,
    MAKE_MENU_VALUE_STRING("Не подключен"), MAKE_MENU_VALUE_STRING("Привод в порядке"), MAKE_MENU_VALUE_STRING("Готовность"),
    MAKE_MENU_VALUE_STRING("Работа"), MAKE_MENU_VALUE_STRING("Ошибка"),
    MAKE_MENU_VALUE_STRING("Предупреждение"), MAKE_MENU_VALUE_STRING("Пользовательский")
);

//! Перечисление .
//MENU_VALUES(menu_enum_,
//    MAKE_MENU_VALUE_STRING(""), MAKE_MENU_VALUE_STRING("")
//);


// Макрос для определения числа элементов перечисления.
#define MENU_ENUM_LEN(MVARR) (sizeof(MVARR)/sizeof(menu_value_t))

/*
 * Значения перечислений элементов меню.
 */
MENU_VALUE_ENUM(menu_val_phase, 0, MENU_ENUM_LEN(menu_enum_phases), menu_enum_phases);
MENU_VALUE_ENUM(menu_val_bool, 0, MENU_ENUM_LEN(menu_enum_bool), menu_enum_bool);
MENU_VALUE_ENUM(menu_val_exc_mode, 0, MENU_ENUM_LEN(menu_enum_exc_mode), menu_enum_exc_mode);
//MENU_VALUE_ENUM(menu_val_en_dis, 0, MENU_ENUM_LEN(menu_enum_en_dis), menu_enum_en_dis);
MENU_VALUE_ENUM(menu_val_stop_mode, 0, MENU_ENUM_LEN(menu_enum_stop_mode), menu_enum_stop_mode);
MENU_VALUE_ENUM(menu_val_prot_action, 0, MENU_ENUM_LEN(menu_enum_prot_action), menu_enum_prot_action);
MENU_VALUE_ENUM(menu_val_dio_in_type, 0, MENU_ENUM_LEN(menu_enum_dio_in_type), menu_enum_dio_in_type);
MENU_VALUE_ENUM(menu_val_dio_out_type, 0, MENU_ENUM_LEN(menu_enum_dio_out_type), menu_enum_dio_out_type);

//MENU_VALUE_ENUM(menu_val_, 0, MENU_ENUM_LEN(menu_enum_), menu_enum_);

#undef MENU_ENUM_LEN


/*
 * Дескрипторы элементов меню.
 */
MENU_DESCRS(menu_descrs) {
    MENU_DESCR(0, 0, "Питание", 0, 0, 0),
        MENU_DESCR(1, 0, "Сеть", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_U_NOM, "Ном. U сети, В", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_I_NOM, "Ном. I сети, А", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, 0, "Якорь", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_U_ROT_NOM, "Ном. U якоря, В", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_I_ROT_NOM, "Ном. I якоря, А", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, 0, "Возбуждение", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_I_EXC, "I возбужд., А", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PHASE, "Фаза возбужд.", MENU_FLAG_DATA, 0, &menu_val_phase),
            MENU_DESCR(2, PARAM_ID_EXC_MODE, "Режим возбужд.", MENU_FLAG_DATA, 0, &menu_val_exc_mode),
    MENU_DESCR(0, 0, "Разгон и торможение", 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_START_TIME, "Время разгона 0-100%, с", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_STOP_TIME, "Время торможения 100-0%, с", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_FAST_STOP_TIME, "Время быстрого торможения 100-0%, с", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_REFERENCE_TIME, "Время изменения задания 0-100%, с", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_STOP_MODE, "Режим останова", MENU_FLAG_DATA, 0, &menu_val_stop_mode),
    MENU_DESCR(0, 0, "ПИД регулятор", 0, 0, 0),
        MENU_DESCR(1, 0, "ПИД якоря", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_ROT_PID_K_P, "Kp", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_ROT_PID_K_I, "Ki", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_ROT_PID_K_D, "Kd", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, 0, "ПИД возбужд.", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PID_K_P, "Kp", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PID_K_I, "Ki", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PID_K_D, "Kd", MENU_FLAG_DATA, 0, 0),
    MENU_DESCR(0, 0, "Запуск и останов", 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_ROT_STOP_TIME, "Время останова якоря, с", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_EXC_STOP_TIME, "Время останова возбужд., с", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_EXC_START_TIME, "Время запуска возбужд., с", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_PHASES_CHECK_TIME, "Время ожидания фаз, мс", MENU_FLAG_DATA, 0, 0),
    MENU_DESCR(0, 0, "Тиристоры", 0, 0, 0),
        MENU_DESCR(1, 0, "Время открытия, мкс", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_TRIACS_PAIRS_OPEN_TIME, "Силовые", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_TRIAC_EXC_OPEN_TIME, "Возбужд.", MENU_FLAG_DATA, 0, 0),
    MENU_DESCR(0, 0, "Защита", 0, 0, 0),
        MENU_DESCR(1, 0, "Тепловая защита", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_THERMAL_OVERLOAD_PROT_ENABLE, "Разрешение", MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, PARAM_ID_THERMAL_OVERLOAD_PROT_TIME_6I, "Время работы при перегрузе 6x, с", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_THERMAL_OVERLOAD_PROT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
        MENU_DESCR(1, 0, "Экстренный останов", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_EMERGENCY_STOP_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
        MENU_DESCR(1, 0, "Напряжение сети", 0, 0, 0),
            MENU_DESCR(2, 0, "Отсечка", 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_U_IN_CUTOFF_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, "Повышение", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
            MENU_DESCR(2, 0, "Понижение", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
        MENU_DESCR(1, 0, "Ток сети", 0, 0, 0),
            MENU_DESCR(2, 0, "Отсечка", 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_I_IN_CUTOFF_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, "Повышение", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
        MENU_DESCR(1, 0, "Напряжение якоря", 0, 0, 0),
            MENU_DESCR(2, 0, "Отсечка", 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_U_ROT_CUTOFF_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, "Повышение", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
        MENU_DESCR(1, 0, "Ток якоря", 0, 0, 0),
            MENU_DESCR(2, 0, "Отсечка", 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_I_ROT_CUTOFF_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, "Повышение", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
        MENU_DESCR(1, 0, "Ток возбуждения", 0, 0, 0),
            MENU_DESCR(2, 0, "Отсечка", 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_I_EXC_CUTOFF_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, "Повышение", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
            MENU_DESCR(2, 0, "Понижение", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_LEVEL_VALUE, "Отклонение, %", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
        MENU_DESCR(1, 0, "Отклонения нулей", 0, 0, 0),
            MENU_DESCR(2, 0, "Ток сети", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_LEVEL_VALUE, "Отклонение, А", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_LEVEL_VALUE, "Отклонение, А", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
            MENU_DESCR(2, 0, "Напряжение якоря", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_LEVEL_VALUE, "Отклонение, В", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_LEVEL_VALUE, "Отклонение, В", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
            MENU_DESCR(2, 0, "Ток якоря", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_LEVEL_VALUE, "Отклонение, А", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_LEVEL_VALUE, "Отклонение, А", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
            MENU_DESCR(2, 0, "Ток возбуждения", 0, 0, 0),
                MENU_DESCR(3, 0, "Уровень ошибки", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_LEVEL_VALUE, "Отклонение, А", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, "Уровень предупреждения", 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_ENABLE, "Включено", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_LEVEL_VALUE, "Отклонение, А", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_LEVEL_TIME_MS, "Время отклонения, мс", MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_LATCH_ENABLE, "Защёлка", MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_ACTION, "Действие", MENU_FLAG_DATA, 0, &menu_val_prot_action),
    MENU_DESCR(0, 0, "Вычисления", 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALC_PHASE_CURRENT, "Вычислять ток для фазы", MENU_FLAG_DATA, 0, &menu_val_phase),
    MENU_DESCR(0, 0, "Коммуникация", 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_MODBUS_BAUD, "Скорость Modbus RTU", MENU_FLAG_DATA, 0, 0),
    MENU_DESCR(0, 0, "Цифровые входа", 0, 0, 0),
        MENU_DESCR(1, 0, "Вход 1", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_1_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_1_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
        MENU_DESCR(1, 0, "Вход 2", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_2_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_2_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
        MENU_DESCR(1, 0, "Вход 3", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_3_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_3_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
        MENU_DESCR(1, 0, "Вход 4", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_4_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_4_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
        MENU_DESCR(1, 0, "Вход 5", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_5_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IN_5_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
    MENU_DESCR(0, 0, "Цифровые выхода", 0, 0, 0),
        MENU_DESCR(1, 0, "Выход 1", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_1_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_1_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
        MENU_DESCR(1, 0, "Выход 2", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_2_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_2_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
        MENU_DESCR(1, 0, "Выход 3", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_3_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_3_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
        MENU_DESCR(1, 0, "Выход 4", 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_4_TYPE, "Тип", MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
            MENU_DESCR(2, PARAM_ID_DIGITAL_OUT_4_INVERSION, "Инверсия", MENU_FLAG_DATA, 0, &menu_val_bool),
    MENU_DESCR(0, 0, "Коэффициенты АЦП", 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ua, "Коэффициент Ua", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ub, "Коэффициент Ub", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Uc, "Коэффициент Uc", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Urot, "Коэффициент Urot", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ia, "Коэффициент Ia", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ib, "Коэффициент Ib", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ic, "Коэффициент Ic", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Irot, "Коэффициент Irot", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Iexc, "Коэффициент Iexc", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Iref, "Коэффициент Iref", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ifan, "Коэффициент Ifan", MENU_FLAG_DATA, 0, 0),
    MENU_DESCR(0, 0, "Калибровочные данные", 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ua, "Значение калибровки Ua", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ub, "Значение калибровки Ub", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Uc, "Значение калибровки Uc", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Urot, "Значение калибровки Urot", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ia, "Значение калибровки Ia", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ib, "Значение калибровки Ib", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ic, "Значение калибровки Ic", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Irot, "Значение калибровки Irot", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Iexc, "Значение калибровки Iexc", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Iref, "Значение калибровки Iref", MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ifan, "Значение калибровки Ifan", MENU_FLAG_DATA, 0, 0),
    //MENU_DESCR(0, 0, "Menu1_1", 0, 0, 0)
};

#endif // PARAMETERS_MENU_H
